/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.umn.interfaces;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2019-04-05")
public class DHTNodePath implements org.apache.thrift.TBase<DHTNodePath, DHTNodePath._Fields>, java.io.Serializable, Cloneable, Comparable<DHTNodePath> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DHTNodePath");

  private static final org.apache.thrift.protocol.TField NODE_FIELD_DESC = new org.apache.thrift.protocol.TField("node", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField VISITED_NODES_FIELD_DESC = new org.apache.thrift.protocol.TField("visitedNodes", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DHTNodePathStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DHTNodePathTupleSchemeFactory());
  }

  public DHTNode node; // required
  public List<DHTNode> visitedNodes; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NODE((short)1, "node"),
    VISITED_NODES((short)2, "visitedNodes");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NODE
          return NODE;
        case 2: // VISITED_NODES
          return VISITED_NODES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NODE, new org.apache.thrift.meta_data.FieldMetaData("node", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DHTNode.class)));
    tmpMap.put(_Fields.VISITED_NODES, new org.apache.thrift.meta_data.FieldMetaData("visitedNodes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DHTNode.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DHTNodePath.class, metaDataMap);
  }

  public DHTNodePath() {
  }

  public DHTNodePath(
    DHTNode node,
    List<DHTNode> visitedNodes)
  {
    this();
    this.node = node;
    this.visitedNodes = visitedNodes;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DHTNodePath(DHTNodePath other) {
    if (other.isSetNode()) {
      this.node = new DHTNode(other.node);
    }
    if (other.isSetVisitedNodes()) {
      List<DHTNode> __this__visitedNodes = new ArrayList<DHTNode>(other.visitedNodes.size());
      for (DHTNode other_element : other.visitedNodes) {
        __this__visitedNodes.add(new DHTNode(other_element));
      }
      this.visitedNodes = __this__visitedNodes;
    }
  }

  public DHTNodePath deepCopy() {
    return new DHTNodePath(this);
  }

  @Override
  public void clear() {
    this.node = null;
    this.visitedNodes = null;
  }

  public DHTNode getNode() {
    return this.node;
  }

  public DHTNodePath setNode(DHTNode node) {
    this.node = node;
    return this;
  }

  public void unsetNode() {
    this.node = null;
  }

  /** Returns true if field node is set (has been assigned a value) and false otherwise */
  public boolean isSetNode() {
    return this.node != null;
  }

  public void setNodeIsSet(boolean value) {
    if (!value) {
      this.node = null;
    }
  }

  public int getVisitedNodesSize() {
    return (this.visitedNodes == null) ? 0 : this.visitedNodes.size();
  }

  public java.util.Iterator<DHTNode> getVisitedNodesIterator() {
    return (this.visitedNodes == null) ? null : this.visitedNodes.iterator();
  }

  public void addToVisitedNodes(DHTNode elem) {
    if (this.visitedNodes == null) {
      this.visitedNodes = new ArrayList<DHTNode>();
    }
    this.visitedNodes.add(elem);
  }

  public List<DHTNode> getVisitedNodes() {
    return this.visitedNodes;
  }

  public DHTNodePath setVisitedNodes(List<DHTNode> visitedNodes) {
    this.visitedNodes = visitedNodes;
    return this;
  }

  public void unsetVisitedNodes() {
    this.visitedNodes = null;
  }

  /** Returns true if field visitedNodes is set (has been assigned a value) and false otherwise */
  public boolean isSetVisitedNodes() {
    return this.visitedNodes != null;
  }

  public void setVisitedNodesIsSet(boolean value) {
    if (!value) {
      this.visitedNodes = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NODE:
      if (value == null) {
        unsetNode();
      } else {
        setNode((DHTNode)value);
      }
      break;

    case VISITED_NODES:
      if (value == null) {
        unsetVisitedNodes();
      } else {
        setVisitedNodes((List<DHTNode>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NODE:
      return getNode();

    case VISITED_NODES:
      return getVisitedNodes();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NODE:
      return isSetNode();
    case VISITED_NODES:
      return isSetVisitedNodes();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DHTNodePath)
      return this.equals((DHTNodePath)that);
    return false;
  }

  public boolean equals(DHTNodePath that) {
    if (that == null)
      return false;

    boolean this_present_node = true && this.isSetNode();
    boolean that_present_node = true && that.isSetNode();
    if (this_present_node || that_present_node) {
      if (!(this_present_node && that_present_node))
        return false;
      if (!this.node.equals(that.node))
        return false;
    }

    boolean this_present_visitedNodes = true && this.isSetVisitedNodes();
    boolean that_present_visitedNodes = true && that.isSetVisitedNodes();
    if (this_present_visitedNodes || that_present_visitedNodes) {
      if (!(this_present_visitedNodes && that_present_visitedNodes))
        return false;
      if (!this.visitedNodes.equals(that.visitedNodes))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_node = true && (isSetNode());
    list.add(present_node);
    if (present_node)
      list.add(node);

    boolean present_visitedNodes = true && (isSetVisitedNodes());
    list.add(present_visitedNodes);
    if (present_visitedNodes)
      list.add(visitedNodes);

    return list.hashCode();
  }

  @Override
  public int compareTo(DHTNodePath other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetNode()).compareTo(other.isSetNode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.node, other.node);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVisitedNodes()).compareTo(other.isSetVisitedNodes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVisitedNodes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.visitedNodes, other.visitedNodes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DHTNodePath(");
    boolean first = true;

    sb.append("node:");
    if (this.node == null) {
      sb.append("null");
    } else {
      sb.append(this.node);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("visitedNodes:");
    if (this.visitedNodes == null) {
      sb.append("null");
    } else {
      sb.append(this.visitedNodes);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (node != null) {
      node.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DHTNodePathStandardSchemeFactory implements SchemeFactory {
    public DHTNodePathStandardScheme getScheme() {
      return new DHTNodePathStandardScheme();
    }
  }

  private static class DHTNodePathStandardScheme extends StandardScheme<DHTNodePath> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DHTNodePath struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.node = new DHTNode();
              struct.node.read(iprot);
              struct.setNodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VISITED_NODES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.visitedNodes = new ArrayList<DHTNode>(_list0.size);
                DHTNode _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new DHTNode();
                  _elem1.read(iprot);
                  struct.visitedNodes.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setVisitedNodesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DHTNodePath struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.node != null) {
        oprot.writeFieldBegin(NODE_FIELD_DESC);
        struct.node.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.visitedNodes != null) {
        oprot.writeFieldBegin(VISITED_NODES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.visitedNodes.size()));
          for (DHTNode _iter3 : struct.visitedNodes)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DHTNodePathTupleSchemeFactory implements SchemeFactory {
    public DHTNodePathTupleScheme getScheme() {
      return new DHTNodePathTupleScheme();
    }
  }

  private static class DHTNodePathTupleScheme extends TupleScheme<DHTNodePath> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DHTNodePath struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetNode()) {
        optionals.set(0);
      }
      if (struct.isSetVisitedNodes()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetNode()) {
        struct.node.write(oprot);
      }
      if (struct.isSetVisitedNodes()) {
        {
          oprot.writeI32(struct.visitedNodes.size());
          for (DHTNode _iter4 : struct.visitedNodes)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DHTNodePath struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.node = new DHTNode();
        struct.node.read(iprot);
        struct.setNodeIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.visitedNodes = new ArrayList<DHTNode>(_list5.size);
          DHTNode _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new DHTNode();
            _elem6.read(iprot);
            struct.visitedNodes.add(_elem6);
          }
        }
        struct.setVisitedNodesIsSet(true);
      }
    }
  }

}

